minor updates to docs (#99)
- fix typo in permissions.rst code snippets
- declare minimum version for new `--jobs `arg
- resolve undefined reference to `HTTPError`