fix: parse clang-tidy output when WarningsAsErrors is asserted
ref cpp-linter/cpp-linter-action#347

Basically, we just needed to account for the `,-warnings-as-errors` appended to the rule name in square brackets.

### Without `WarningsAsErrors`
```text
tests/demo/demo.cpp:2:1: error: included header demo.hpp is not used directly [misc-include-cleaner]
```
### With `WarningsAsErrors`
```text
tests/demo/demo.cpp:2:1: error: included header demo.hpp is not used directly [misc-include-cleaner,-warnings-as-errors]
```